import { Check, Copy, Download, FileText, ShieldCheck } from 'lucide-react'
import { pdfReportUrl, Report as ReportData } from '../lib/api'

export function Report({ report, jobId }: { report: ReportData; jobId: string }) {
  const copy = (value: string) => void navigator.clipboard?.writeText(value)
  return <div className="page report-page">
    <div className="page-title-row"><div><span className="section-kicker">Forensic report</span><h1>Case findings</h1><p>{report.case_metadata?.case_number || 'Case reference unavailable'} · Generated {new Date(report.generated_at).toLocaleString()} · {report.tool}</p></div><a className="secondary-button" href={pdfReportUrl(jobId)} download><Download size={16} /> Download PDF Report</a></div>
    <div className="report-layout">
      <section className="report-card"><Heading icon={<FileText size={18} />} title="Disk metadata" /><DataRows rows={[["Source filename", report.disk_metadata.filename], ["Image size", `${(report.disk_metadata.size_bytes / 1024 / 1024).toFixed(2)} MB`], ["Processed", new Date(report.disk_metadata.processed_at).toLocaleString()], ["MD5", report.disk_metadata.md5], ["SHA-256", report.disk_metadata.sha256]]} monoKeys={['MD5', 'SHA-256']} onCopy={copy} /></section>
      <section className="report-card"><Heading icon={<ShieldCheck size={18} />} title="Device identification" /><DataRows rows={[["Manufacturer", report.device_identification.vendor_name], ["Confidence", report.device_identification.detection_confidence], ["Signature offset", String(report.device_identification.signature_found_at_offset ?? '—')], ["Parser status", report.device_identification.fully_implemented ? 'Fully implemented' : 'Detection only']]} /></section>
      <section className="report-card wide"><Heading icon={<Check size={18} />} title="Recovery statistics" /><DataRows rows={[["Total frames scanned", String(report.recovery_stats.total_frames_scanned)], ["Valid frames", String(report.recovery_stats.valid_frames)], ["Rejected frames", String(report.recovery_stats.invalid_frames)], ["Frames in sequences", String(report.recovery_stats.frames_in_sequences)], ["Gaps detected", String(report.recovery_stats.gaps_detected)], ["Recovery rate", `${report.recovery_stats.recovery_rate.recovery_rate_pct ?? 'N/A'}%`]]} /><div className="rejection-list"><span className="section-kicker">Rejection reasons</span>{Object.entries(report.recovery_stats.invalid_by_rejection_reason).map(([reason, count]) => <div key={reason}><span>{reason}</span><strong>{count}</strong></div>)}</div></section>
      <section className="report-card wide"><Heading icon={<ShieldCheck size={18} />} title="Chain of custody" /><p className="custody-copy">{report.chain_of_custody.processing_note}</p><p className="custody-caption">Tamper-evident hash-chained custody log — the same cryptographic primitive blockchains use for immutability. This is blockchain-style hash-chaining, not a blockchain.</p><DataRows rows={[["Acquired by", report.chain_of_custody.acquired_by], ["Acquired at", new Date(report.chain_of_custody.acquired_at).toLocaleString()], ["Tool", report.chain_of_custody.tool], ["Hash algorithms", report.chain_of_custody.hash_algorithms.join(' · ')], ["Previous entry hash", report.chain_of_custody.prev_entry_hash || 'Genesis entry — no prior record'], ["This entry hash", report.chain_of_custody.entry_hash || 'Legacy report — entry hash unavailable']]} /></section>
      <section className="report-card wide"><Heading icon={<FileText size={18} />} title="Recovered evidence index" /><p className="custody-copy">Every output artifact with its timestamp range, frame count, and forensic hashes.</p><div className="preview-evidence-list">{report.recovered_files.map((file) => <div key={file.filename}><strong>{file.filename}</strong><span>{file.start_ts} to {file.end_ts} · {file.frame_count} frames</span><small>SHA-256 {file.sha256} · MD5 {file.md5}</small></div>)}</div></section>
      <section className="report-card wide"><Heading icon={<FileText size={18} />} title="Methodology appendix" /><p className="custody-copy">Signature detection scans the source image for vendor-specific markers and frame magic, allowing the correct parser to be selected without modifying the original media. Dual-signature validation checks independent header and footer markers, declared sizes, and checksums before a frame is accepted. Adaptive temporal sequencing orders valid frames by channel and timestamp, learns the running median inter-frame interval, and flags unusually large time or frame-number discontinuities as gaps.</p></section>
      <section className="report-card wide draft-preview"><Heading icon={<ShieldCheck size={18} />} title="Draft Section 65B Certificate" /><p className="custody-copy">Technical content for review and completion by the person in lawful control of the source device or system.</p><DataRows rows={[["Case reference", report.case_metadata?.case_number || 'Case reference unavailable'], ["Device / system", `${report.device_identification.vendor_name} DVR/NVR`], ["Source SHA-256", report.disk_metadata.sha256], ["Extraction date/time", report.generated_at], ["Examiner / custodian name", '________________________________________']]} /><p className="draft-disclaimer">DRAFT ONLY - REQUIRES HUMAN REVIEW AND SIGNATURE<br /><br />This is a draft prepared by DeepTrace for review. It must be reviewed and signed by the person in lawful control of the source device/system before submission as evidence under Section 65B, Indian Evidence Act.</p><div className="signature-lines">Signature of lawful custodian / investigating officer ____________________ &nbsp;&nbsp; Date __________________</div></section>
    </div>
  </div>
}
function Heading({ icon, title }: { icon: React.ReactNode; title: string }) { return <div className="report-card-heading">{icon}<h2>{title}</h2></div> }
function DataRows({ rows, monoKeys = [], onCopy }: { rows: string[][]; monoKeys?: string[]; onCopy?: (value: string) => void }) { return <dl className="data-rows">{rows.map(([key, value]) => <div key={key}><dt>{key}</dt><dd className={monoKeys.includes(key) ? 'mono' : ''}>{value}{onCopy && monoKeys.includes(key) && <button className="copy-inline" onClick={() => onCopy(value)} title="Copy"><Copy size={13} /></button>}</dd></div>)}</dl> }
